t_hashtab.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include `test-harness.h`
#include `dbprim.h`
#include `dbprim_int.h`
Data Structures
struct moves_s
struct iter_s
Defines
#define FLUSH_THRESHOLD
#define _hw(n, m, s)
#define RSF_INHIBIT
#define RSF_RESIZE
#define HASH_ENT_CNT
#define HASH_MOVE_CNT
#define HASH_REMOVE_CNT
#define VISIT_INIT
Functions
static unsigned long hamming (unsigned long bits)
static unsigned long t_hash (hash_table_t *tab, db_key_t *key)
static unsigned long t_comp (hash_table_t *tab, db_key_t *key1, db_key_t *key2)
static unsigned long t_resize (hash_table_t *tab, unsigned long new)
static unsigned long t_iter (hash_table_t *tab, hash_entry_t *ent, struct iter_s *iter)
int main (int argc, char **argv)
Variables
static unsigned int rsize_flags
static unsigned long rsize_new
static unsigned long rsize_err
static db_key_t keys []
static struct moves_s moves []
static int removes []
Define Documentation
#define _hw(n, m, s)
Referenced by hamming().
#define FLUSH_THRESHOLD
Definition at line 35 of file t_hashtab.c.
Referenced by main().
#define HASH_ENT_CNT
Definition at line 121 of file t_hashtab.c.
Referenced by main().
#define HASH_MOVE_CNT
Definition at line 139 of file t_hashtab.c.
Referenced by main().
#define HASH_REMOVE_CNT
Definition at line 143 of file t_hashtab.c.
Referenced by main().
#define RSF_INHIBIT
Definition at line 86 of file t_hashtab.c.
Referenced by main(), and t_resize().
#define RSF_RESIZE
Definition at line 87 of file t_hashtab.c.
Referenced by main(), and t_resize().
#define VISIT_INIT
Definition at line 151 of file t_hashtab.c.
Referenced by main().
Function Documentation
static unsigned long hamming (unsigned long bits) [static]
Definition at line 39 of file t_hashtab.c.
References _hw.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 170 of file t_hashtab.c.
References iter_s::elem, FLUSH_THRESHOLD, hamming(), HASH_ENT_CNT, HASH_FLAG_AUTOGROW, HASH_FLAG_AUTOSHRINK, HASH_MOVE_CNT, HASH_REMOVE_CNT, he_init(), ht_add(), ht_count, ht_find(), ht_flags, ht_flush(), ht_free(), ht_init(), ht_iter(), ht_modulus, ht_move(), ht_remove(), ht_resize(), _hash_table_s::ht_table, moves, removes, RSF_INHIBIT, RSF_RESIZE, rsize_err, rsize_flags, rsize_new, t_comp(), t_hash(), t_iter(), t_resize(), VISIT_INIT, and iter_s::visited.
static unsigned long t_comp (hash_table_t * tab, db_key_t * key1, db_key_t * key2) [static]
Definition at line 70 of file t_hashtab.c.
References dk_key, and dk_len.
Referenced by main().
static unsigned long t_hash (hash_table_t * tab, db_key_t * key) [static]
Definition at line 53 of file t_hashtab.c.
References dk_key, and dk_len.
Referenced by main().
static unsigned long t_iter (hash_table_t * tab, hash_entry_t * ent, struct iter_s * iter) [static]
Definition at line 154 of file t_hashtab.c.
References iter_s::elem, iter_s::err, he_value, and iter_s::visited.
Referenced by main().
static unsigned long t_resize (hash_table_t * tab, unsigned long new) [static]
Definition at line 94 of file t_hashtab.c.
References RSF_INHIBIT, RSF_RESIZE, rsize_err, rsize_flags, and rsize_new.
Referenced by main().
Variable Documentation
db_key_t keys[] [static]
Definition at line 103 of file t_hashtab.c.
struct moves_s moves[] [static]
Referenced by main().
int removes[] [static]
Definition at line 141 of file t_hashtab.c.
Referenced by main().
unsigned long rsize_err [static]
Definition at line 90 of file t_hashtab.c.
Referenced by main(), and t_resize().
unsigned int rsize_flags [static]
Definition at line 84 of file t_hashtab.c.
Referenced by main(), and t_resize().
unsigned long rsize_new [static]
Definition at line 89 of file t_hashtab.c.
Referenced by main(), and t_resize().