t_linklists.c File Reference
#include <stdio.h>
#include `test-harness.h`
#include `dbprim.h`
#include `dbprim_int.h`
Data Structures
struct tdata_s
struct tmove_s
struct iter_desc
Defines
#define LINK_ELEM_CNT
#define LINK_MOVE_CNT
#define LINK_REMOVE_CNT
#define LINK_ITER_CNT
#define LINK_FLUSH_CNT
#define ChkOrder(name, order, fatal, go)
Functions
static unsigned long t_comp (db_key_t *key, void *comp)
static unsigned long t_iter (link_head_t *head, link_elem_t *elem, void *extra)
int main (int argc, char **argv)
Variables
tdata_s tdata []
int order_add []
tmove_s tmove []
int order_move []
int tremove []
int order_remove []
iter_desc desc_iter []
iter_desc desc_flush []
int order_flush [][2]
Define Documentation
#define ChkOrder(name, order, fatal, go)
Definition at line 117 of file t_linklists.c.
Referenced by main().
#define LINK_ELEM_CNT
Definition at line 44 of file t_linklists.c.
Referenced by main().
#define LINK_FLUSH_CNT
Definition at line 115 of file t_linklists.c.
Referenced by main().
#define LINK_ITER_CNT
Definition at line 103 of file t_linklists.c.
Referenced by main().
#define LINK_MOVE_CNT
Definition at line 59 of file t_linklists.c.
Referenced by main().
#define LINK_REMOVE_CNT
Definition at line 65 of file t_linklists.c.
Referenced by main().
Function Documentation
int main (int argc, char ** argv)
Definition at line 139 of file t_linklists.c.
References ChkOrder, DB_KEY_INIT, dk_len, iter_desc::elem, iter_desc::err, iter_desc::expected, iter_desc::flags, le_init(), LINK_ELEM_CNT, LINK_FLUSH_CNT, LINK_ITER_CNT, LINK_MOVE_CNT, LINK_REMOVE_CNT, ll_add(), ll_find(), ll_flush(), ll_init(), ll_iter(), ll_move(), ll_remove(), order_add, order_flush, order_move, order_remove, iter_desc::start, t_comp(), t_iter(), tdata, tmove, tremove, and iter_desc::visited.
static unsigned long t_comp (db_key_t * key, void * comp) [static]
Definition at line 70 of file t_linklists.c.
References dk_len.
static unsigned long t_iter (link_head_t * head, link_elem_t * elem, void * extra) [static]
Definition at line 85 of file t_linklists.c.
References iter_desc::elem, iter_desc::err, le_object, and iter_desc::visited.
Variable Documentation
struct iter_desc desc_flush[]
Definition at line 105 of file t_linklists.c.
struct iter_desc desc_iter[]
Definition at line 95 of file t_linklists.c.
int order_add[]
Definition at line 46 of file t_linklists.c.
Referenced by main().
int order_flush[][2]
Definition at line 110 of file t_linklists.c.
Referenced by main().
int order_move[]
Definition at line 61 of file t_linklists.c.
Referenced by main().
int order_remove[]
Definition at line 67 of file t_linklists.c.
Referenced by main().
struct tdata_s tdata[]
Referenced by main().
struct tmove_s tmove[]
Referenced by main().
int tremove[]
Definition at line 63 of file t_linklists.c.
Referenced by main().