t_redblack.c File Reference
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include `test-harness.h`
#include `dbprim.h`
#include `dbprim_int.h`
Data Structures
struct flush_test
struct iter_test
Defines
#define RBT_ELEM_CNT
#define RBT_ELEM_MASK
#define selnode(n, rev)
#define n_debargs(node)
#define STOP_RETURN
#define VISIT_RETURN
#define ITER_TRIALS
Functions
static void _make_pre (rb_node_t *node, int *order, int *idx, int reverse, unsigned long *visited)
static void _make_in (rb_node_t *node, int *order, int *idx, int reverse, unsigned long *visited)
static void _make_post (rb_node_t *node, int *order, int *idx, int reverse, unsigned long *visited)
static void make_order (rb_tree_t *tree, int *order, unsigned long flags, unsigned long *visited)
static int comp_order (int *o1, int *o2)
static int treecheck (rb_node_t *node, rb_node_t *parent, int bh, int *tbhp)
static long t_comp (rb_tree_t *tree, db_key_t *key1, db_key_t *key2)
static unsigned long t_flush (rb_tree_t *tree, rb_node_t *node, struct flush_test *ft)
static unsigned long t_iter (rb_tree_t *tree, rb_node_t *node, struct iter_test *it)
int main (int argc, char **argv)
Define Documentation
#define ITER_TRIALS
Definition at line 268 of file t_redblack.c.
Referenced by main().
#define n_debargs(node)
Definition at line 134 of file t_redblack.c.
Referenced by treecheck().
#define RBT_ELEM_CNT
Definition at line 36 of file t_redblack.c.
Referenced by comp_order(), and main().
#define RBT_ELEM_MASK
Definition at line 42 of file t_redblack.c.
Referenced by main().
#define selnode(n, rev)
Referenced by _make_in().
#define STOP_RETURN
Definition at line 239 of file t_redblack.c.
Referenced by main(), t_flush(), and t_iter().
#define VISIT_RETURN
Definition at line 240 of file t_redblack.c.
Referenced by main(), t_flush(), and t_iter().
Function Documentation
static void _make_in (rb_node_t * node, int * order, int * idx, int reverse, unsigned long * visited) [static]
Definition at line 62 of file t_redblack.c.
References rn_value, and selnode.
Referenced by make_order().
static void _make_post (rb_node_t * node, int * order, int * idx, int reverse, unsigned long * visited) [static]
Definition at line 77 of file t_redblack.c.
References rn_left, rn_right, and rn_value.
Referenced by make_order().
static void _make_pre (rb_node_t * node, int * order, int * idx, int reverse, unsigned long * visited) [static]
Definition at line 46 of file t_redblack.c.
References rn_left, rn_right, and rn_value.
Referenced by make_order().
static int comp_order (int * o1, int * o2) [static]
Definition at line 116 of file t_redblack.c.
References RBT_ELEM_CNT.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 293 of file t_redblack.c.
References comp_order(), DB_KEY_INIT, dk_len, iter_test::idx, ITER_TRIALS, iter_test::last_node, make_order(), iter_test::order, RBT_ELEM_CNT, RBT_ELEM_MASK, RBT_ORDER_MASK, rn_init(), rn_key, rt_add(), rt_count, rt_find(), rt_flush(), rt_init(), rt_iter(), rt_next(), rt_remove(), rt_root, iter_test::stop_node, flush_test::stop_node, STOP_RETURN, t_comp(), t_flush(), t_iter(), treecheck(), VISIT_RETURN, iter_test::visited, and flush_test::visited.
static void make_order (rb_tree_t * tree, int * order, unsigned long flags, unsigned long * visited) [static]
Definition at line 93 of file t_redblack.c.
References _make_in(), _make_post(), _make_pre(), DB_FLAG_REVERSE, RBT_ORDER_IN, RBT_ORDER_POST, RBT_ORDER_PRE, and rt_root.
Referenced by main().
static long t_comp (rb_tree_t * tree, db_key_t * key1, db_key_t * key2) [static]
Definition at line 228 of file t_redblack.c.
References dk_len.
static unsigned long t_flush (rb_tree_t * tree, rb_node_t * node, struct flush_test * ft) [static]
Definition at line 244 of file t_redblack.c.
References dk_len, rn_key, flush_test::stop_node, STOP_RETURN, VISIT_RETURN, and flush_test::visited.
Referenced by main().
static unsigned long t_iter (rb_tree_t * tree, rb_node_t * node, struct iter_test * it) [static]
Definition at line 272 of file t_redblack.c.
References dk_len, iter_test::idx, iter_test::last_node, iter_test::order, rn_key, iter_test::stop_node, STOP_RETURN, VISIT_RETURN, and iter_test::visited.
static int treecheck (rb_node_t * node, rb_node_t * parent, int bh, int * tbhp) [static]
Definition at line 140 of file t_redblack.c.
References dk_len, n_debargs, rn_isblack, rn_isred, rn_key, _rb_node_s::rn_left, _rb_node_s::rn_parent, and _rb_node_s::rn_right.
Referenced by main().