t_smat.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include `test-harness.h`
#include `dbprim.h`
#include `dbprim_int.h`
Data Structures
struct assoc_s
Defines
#define SMAT_HEAD_CNT
#define SMAT_HEAD_MASK
#define SMAT_ASSOC_CNT
#define set_assoc(ass, row, column)
#define clr_assoc(ass, row, column)
#define chk_assoc(ass, row, column)
Functions
static void set_ones (struct assoc_s *assoc)
static void set_zeros (struct assoc_s *assoc)
static int check_zeros (struct assoc_s *assoc)
int main (int argc, char **argv)
Variables
static smat_head_t rows [SMAT_HEAD_CNT]
static smat_head_t columns [SMAT_HEAD_CNT]
static struct assoc_s associations
Define Documentation
#define chk_assoc(ass, row, column)
Definition at line 88 of file t_smat.c.
Referenced by main().
#define clr_assoc(ass, row, column)
Definition at line 86 of file t_smat.c.
Referenced by main().
#define set_assoc(ass, row, column)
Definition at line 84 of file t_smat.c.
Referenced by main().
#define SMAT_ASSOC_CNT
Definition at line 48 of file t_smat.c.
Referenced by main().
#define SMAT_HEAD_CNT
Definition at line 34 of file t_smat.c.
Referenced by check_zeros(), main(), set_ones(), and set_zeros().
#define SMAT_HEAD_MASK
Definition at line 40 of file t_smat.c.
Referenced by set_ones().
Function Documentation
static int check_zeros (struct assoc_s * assoc) [static]
Definition at line 72 of file t_smat.c.
References assoc_s::assoc, and SMAT_HEAD_CNT.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 92 of file t_smat.c.
References associations, check_zeros(), chk_assoc, clr_assoc, LINK_LOC_HEAD, se_object, set_assoc, set_ones(), set_zeros(), sh_init(), SMAT_ASSOC_CNT, SMAT_HEAD_CNT, SMAT_LOC_FIRST, SMAT_LOC_SECOND, st_add(), st_count, st_find(), st_init(), st_modulus, and st_remove().
static void set_ones (struct assoc_s * assoc) [static]
Definition at line 52 of file t_smat.c.
References assoc_s::assoc, SMAT_HEAD_CNT, and SMAT_HEAD_MASK.
Referenced by main().
static void set_zeros (struct assoc_s * assoc) [static]
Definition at line 62 of file t_smat.c.
References assoc_s::assoc, and SMAT_HEAD_CNT.
Referenced by main().
Variable Documentation
struct assoc_s associations [static]
Referenced by main().
smat_head_t columns[SMAT_HEAD_CNT] [static]
Definition at line 43 of file t_smat.c.
smat_head_t rows[SMAT_HEAD_CNT] [static]
Definition at line 42 of file t_smat.c.